name: RandomItemDropper
version: 1.1.0
author: EylexLive
main: io.github.eylexlive.randomitemdropper.RandomItemDropper
api-version: 1.16
commands:
  rid:
    aliases: [randomitemdropper, itemdropper, dropper]